import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "standalone",
  // The Prisma generated client (node_modules/.prisma/client, including the
  // native query engine binary) is required at runtime by the API routes.
  // It is generated by the root `postinstall` script (`prisma generate`) on
  // every install, and this option guarantees the generated files are traced
  // into the runtime bundles (standalone output / serverless functions).
  // db/supabase-schema.sql is read at runtime by /api/admin/supabase (the
  // in-app Supabase provisioning panel); db/custom.db (the data-backend
  // switch database) and prisma/schema.prisma (the anchor Prisma resolves
  // relative SQLite URLs against) are traced so `file:../db/custom.db`
  // works identically in dev, the standalone server and serverless functions.
  outputFileTracingIncludes: {
    "/**": [
      "./node_modules/.prisma/**/*",
      "./db/supabase-schema.sql",
      "./db/custom.db",
      "./prisma/schema.prisma",
    ],
  },
  // Type checking is ENFORCED at build time (no ignoreBuildErrors override):
  // the source tree passes `tsc --noEmit` cleanly, so any future type
  // regression fails the build instead of shipping silently.
  reactStrictMode: false,
  // Hide the dev-tools indicator so it never covers the mobile bottom nav.
  devIndicators: false,
};

export default nextConfig;
